apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub1
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: host
    value: "amqp://broker:5672" 
  - name: durable
    value: true
scopes:
  - frontend
  - backend