apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: custom_resiliency
scopes:
  - saturn
spec:
  policies:
    timeouts:
      default: 5s

    circuitBreakers:
      default:
        maxRequests: 1
        timeout: 30s 
        trip: consecutiveFailures >= 5

    retries:
      default:
        policy: constant
        duration: 1s
        maxRetries: -1
  targets:
    apps:
      neptune:
        timeout: default
        circuitBreaker: default
        # retry: default

    
